/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maze.gui;

import dkeep.logic.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import java.awt.Color;

/**
 *
 * @author Gon√ßaloSilva
 */
public class Interface extends javax.swing.JFrame {

    public int[][] dragonPos;
    public State s1;
    


    /**
     * Creates new form Interface
     */
    public Interface() {
    	dragonPos=new int[6][2];
		dragonPos[0][0]=4;
		dragonPos[0][1]=1;
		dragonPos[1][0]=8;
		dragonPos[1][1]=8;
		dragonPos[2][0]=1;
		dragonPos[2][1]=7;
		dragonPos[3][0]=8;
		dragonPos[3][1]=1;
		dragonPos[4][0]=8;
		dragonPos[4][1]=4;
		dragonPos[5][0]=5;
		dragonPos[5][1]=6;

        initComponents();
        setLocationRelativeTo(null); //coloca no centro do ecra
      //  pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNumber = new javax.swing.JTextField();
        btnLeft = new javax.swing.JButton();
        btnLeft.setEnabled(false);
        btnNewGame = new javax.swing.JButton();
        btnUp = new javax.swing.JButton();
        btnUp.setEnabled(false);
        btnRight = new javax.swing.JButton();
        btnRight.setEnabled(false);
        btnDown = new javax.swing.JButton();
        btnDown.setEnabled(false);
        lblMessage = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        checkBox = new javax.swing.JCheckBox();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Number of Dragons");

        txtNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumber.setText("1");
        txtNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberActionPerformed(evt);
            }
        });

        btnLeft.setText("LEFT");
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });

        btnNewGame.setText("NEW GAME");
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });

        btnUp.setText("UP");
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });

        btnRight.setText("RIGHT");
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });

        btnDown.setText("DOWN");
        btnDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownActionPerformed(evt);
            }
        });

        lblMessage.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText("Can start a New Game");

        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        
        checkDiagonally = new JCheckBox("Diagonnaly");
        
        painel = new Display();
        painel.setBackground(Color.WHITE);
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(12)
        					.addComponent(lblMessage, GroupLayout.PREFERRED_SIZE, 344, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())
        				.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        					.addGroup(layout.createSequentialGroup()
        						.addComponent(jLabel1)
        						.addGap(18)
        						.addComponent(txtNumber, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
        						.addContainerGap(576, Short.MAX_VALUE))
        					.addGroup(layout.createSequentialGroup()
        						.addGap(24)
        						.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        							.addGroup(layout.createSequentialGroup()
        								.addComponent(checkDiagonally)
        								.addPreferredGap(ComponentPlacement.RELATED, 490, Short.MAX_VALUE))
        							.addGroup(layout.createSequentialGroup()
        								.addComponent(painel, GroupLayout.PREFERRED_SIZE, 377, GroupLayout.PREFERRED_SIZE)
        								.addGap(18)
        								.addGroup(layout.createParallelGroup(Alignment.LEADING)
        									.addGroup(layout.createSequentialGroup()
        										.addPreferredGap(ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
        										.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        											.addGroup(layout.createSequentialGroup()
        												.addGroup(layout.createParallelGroup(Alignment.LEADING)
        													.addComponent(btnExit)
        													.addComponent(btnDown)
        													.addComponent(btnUp))
        												.addGap(12))
        											.addGroup(layout.createSequentialGroup()
        												.addComponent(btnNewGame)
        												.addGap(3))))
        									.addGroup(layout.createSequentialGroup()
        										.addGap(18)
        										.addComponent(btnLeft)))))
        						.addPreferredGap(ComponentPlacement.RELATED)
        						.addComponent(btnRight)
        						.addGap(106)))))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(txtNumber, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(9)
        					.addComponent(checkDiagonally)
        					.addGap(18)
        					.addComponent(painel, GroupLayout.PREFERRED_SIZE, 315, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(37)
        					.addComponent(btnNewGame)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(btnUp)
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(btnRight)
        						.addComponent(btnLeft))
        					.addGap(18)
        					.addComponent(btnDown)
        					.addPreferredGap(ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
        					.addComponent(btnExit)))
        			.addGap(32)
        			.addComponent(lblMessage, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        painel.setLayout(null);
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberActionPerformed

//GEN-LAST:event_btnNewGameActionPerformed
    private void gameLogic(String move) {
        if (s1.isState()) {
            if (s1.movHero(move)) {
                if (s1.isState()) {
                    s1.movDragon();
                }
              
               if(s1.getE1().getSaida() == painel.getNumDragons()) { // se os dragoes j· estiverem todos mortos, a porta abre e muda a imagem
            	   this.painel.changeImage("door_open.jpg");
               }
               imprimir(s1.getE1(), s1.getListD(), s1.getH1(), s1.getS1(),s1.getM1().getMap());
            }
            if (s1.getM1().getFinish() || !s1.getH1().isLife()) {
            	btnDown.setEnabled(false);
            	btnUp.setEnabled(false);
            	btnRight.setEnabled(false);
            	btnLeft.setEnabled(false);

            	return;
            }
        }
    }

    private void imprimir(Exiit e1, ArrayList<Dragon> dl1, Hero h1, Sword s1,char [][] map) {
       
        this.painel.PosHero(h1.getX(), h1.getY());
        this.painel.PosSword(s1.getX(), s1.getY());
        this.painel.PosExit(e1.getX(), e1.getY()); 
      
        if(!h1.isHeroHas()) {
        	  this.painel.PosSword(s1.getX(), s1.getY());
        } else {
        	 this.painel.PosSword(9, 9);  // se o heroi tiver espada, ela vai para 9 vs 9 e o Display nao imprime
        }
        for(int i = 0; i < this.painel.getNumDragons(); i++) {
        	if(dl1.get(i).getLife()) {
        	this.painel.PosDragon(i, dl1.get(i).getX(), dl1.get(i).getY());
        	} else {
        		this.painel.PosDragon(i, 9, 9);   //se estiver morto vai para a posiÁ„o 9 vs 9, e o Display sabe que est· morto
        	}
        }
   
    }
    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        gameLogic("w");
    }//GEN-LAST:event_btnUpActionPerformed
    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
    	btnDown.setEnabled(true);
    	btnUp.setEnabled(true);
    	btnRight.setEnabled(true);
    	btnLeft.setEnabled(true);
    	painel.setAtivo(true);
 	   this.painel.changeImage("door_closed.jpg");

    	s1 = new State();
        int numDragons = Integer.parseInt(txtNumber.getText());
       
        if (numDragons > 6 || numDragons < 1) {
            JOptionPane.showMessageDialog(null, "Numero de Dragıes entre 1 e 6");
            return;
        }  
        painel.setNumDragons(numDragons);
        s1.new_game(numDragons, dragonPos);
        
   //-------VERIFICA SE … PARA ANDAR NA DIAGONAL--------------------------------------
        if(checkDiagonally.isSelected()) {
        	s1.getM1().setTipoMov(true);
        }
        else {
        	s1.getM1().setTipoMov(false);
        }
   //----------------------------------------------------------------------------------
    imprimir(s1.getE1(), s1.getListD(), s1.getH1(), s1.getS1(),s1.getM1().getMap());
      /* this.painel.PosExit(s1.getE1().getX(), s1.getE1().getY());
       this.painel.PosSword(s1.getS1().getX(), s1.getS1().getY());
       this.painel.PosHero(s1.getH1().getX(), s1.getH1().getY());*/
        
    }
    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        gameLogic("d");
    	
    }//GEN-LAST:event_btnRightActionPerformed

    private void btnDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownActionPerformed
        gameLogic("s");
    }//GEN-LAST:event_btnDownActionPerformed

    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
        gameLogic("a");
    }//GEN-LAST:event_btnLeftActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
            	new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDown;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JButton btnRight;
    private javax.swing.JButton btnUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTextField txtNumber;
    private JCheckBox checkBox;
    private Display painel;
    private JCheckBox checkDiagonally;
}
